services:
  mariadb:
    build: ./mariadb
    volumes:
      - mariadb_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wpuser
      MYSQL_PASSWORD: password123
    networks:
      - wordpress-network
    
  wordpress:
    build: ./wordpress
    ports:
      - "8080:80"
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - wordpress-network
    environment:
      WORDPRESS_DB_HOST: mariadb:3306
      WORDPRESS_DB_USER: wpuser
      WORDPRESS_DB_PASSWORD: password123
      WORDPRESS_DB_NAME: wordpress
      WP_ADMIN_USER: admin
      WP_ADMIN_PASSWORD: adminpassword
      WP_ADMIN_EMAIL: admin@admin.com


volumes:
  mariadb_data:
  wordpress_data:

networks:
  wordpress-network:
    driver: bridge